CREATE TABLE users (
	id serial PRIMARY KEY,
	name VARCHAR(100),
	email text UNIQUE NOT NULL,
	entries BIGINT DEFAULT 0,
	joined TIMESTAMP NOT NULL
);


CREATE TABLE login (
	id SERIAL PRIMARY KEY,
	hash VARCHAR(100) NOT NULL,
	email TEXT UNIQUE NOT NULL
);